services:
  postgres:
    image: postgres:14-alpine
    container_name: l0_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 5


  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: l0_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    restart: always


  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: l0_kafka
    depends_on:
      - zookeeper
    ports:
      - "9292:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9292,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: always

  
  kafka-setup:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - kafka
    command: >
      bash -c "
        echo 'Ожидание готовности Kafka...' &&
        cub kafka-ready -b kafka:29092 1 20 &&
        echo 'Kafka готова.' &&
        kafka-topics --create --topic orders --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
      "
    restart: on-failure


  app:
    container_name: l0_app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      kafka-setup:
        condition: service_completed_successfully
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_PORT: "5432"
      KAFKA_BROKERS: "kafka:29092"
    restart: always